### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/ecommerce-pattern-library#11]
Style & design — 1
- I think the components look nice, and I thought a reasonable amount ahead of time about how things would look at various screen sizes; but a lot of choices were stylistic, and not semantically or accessibly appropriate. As a designer, I specifically failed this component for so many people right from the creation of my wire frames. The hover states aren't particularly good for contrast, changing the header style dramatically was clearly unsuccessful in execution.

Patterns — 1
- I started off my patterns feeling pretty confident, and many of the initial components work well. But the larger card, table, and form components were frankly not well done at all. I thought I planned well for many components, but by including (for example) unit sizings directly in patterns, I severely limited how and where they could be applied.

Explanations — 2
- I think I do an adequate job of explaining my patterns, but in practice, how you could reasonably be expected to apply them doesn't always match the optimistic descriptions.

Accessibility — 0
- The site just isn't accessible. The most obvious example of this (at the time of writing this rationale, which is likely to reflect the product you're seeing now) is the header, where layers of z-indexed nonsense means a user can't reliably even click to navigate the site, nevermind with a keyboard or screenreader. The focus states are abysmal. The forms don't follow accessible guidelines at all, so thanks a heap for designing them that way, January MacKenzie. There are tags, occasionally even in the right places, but overall, it's a nightmare from a user standpoint. (The only caveat I can give is that the file sizes are small, while the fonts are big. I realize that removing the unused images would reduce the size too, but it still performs well load-time wise.) 

Semantics — 2
- I generally use good semantics, but I'm still catching problems in my YAML files where I used hyphens instead of underscores. I also often misuse ARIA components, and have tabindex in FAR too many places. The more I think about it, a 2 might be too generous.

Responsiveness — 2
- Visually, the site responds okay to screen resizing, until it hits 280 pixels and below; then things extremely noticeably break down. As well, you'll notice the mini forms (like the email newsletter in the footer) are often slightly off from the button they're paired with. I muddled some with the css content you give us (Modulifier etc.) to address this, but my fixes were pretty brute force.

Code quality — 1
- Well, at least thanks to auto-indent and a little common sense, the indentation is probably spot on in my files. I am not happy with my code, though. I keep saying it, but I am genuinely very excited to redo this project over the summer, so I can make clean code. :)

Git & commits — 2.5
- I have a lot of commits, and I do my best to be descriptive with  the commit messages and comments. That said, I tend not to push my code very frequently, which is something I need to break the habit of.

---
**This makes for a grand total of 11.5/24 (48%) which is absolutely the right grade.** 

I don't want you to think I didn't spend any time on this, or that I didn't enjoy the project, because neither of those are true! I just don't think the end result is particularly good at this stage, and I want you to know that I know that. But I'm really satisfied with how much I learned from this, so thank you so much for everything. It's been a blast.

**Comment by thomasjbradley** [comment]
Thank you for your honesty—and for actually completing the project this term. Even if it’s not as good as you had hoped.

**Comment by MacKenzieRose** [comment]
Woah, you mark quickly! 🥇 

Have a wonderful summer :) Even if you're not our teacher in the fall, please come say hi :)

And now, off to actually learning how to do all of this properly 🎉
