### ISSUE TITLE
Liquid tag not recognized

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/ecommerce-pattern-library#3]
Hi @thomasjbradley!

Every time I commit code, I get a fun email like so:

<img width="905" alt="Screen Shot 2020-02-03 at 9 03 46 PM" src="https://user-images.githubusercontent.com/19557909/73707208-d9d15680-46c8-11ea-8a39-b82d2feaef4c.png">

Do you know what's causing it?

Cheers!

MacKenzie

**Comment by thomasjbradley** [comment]
On GitHub’s website for this repo, go to "Settings" and shut off GitHub Pages, set it to "None" instead of `master`.

It’s because of this we’re using Netfliy for hosting instead of GitHub. GitHub’s Jekyll hosting is limited to only a small set of plugins.

**Comment by MacKenzieRose** [comment]
Makes sense; thank you!! :)
