### ISSUE TITLE
Grades

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/ecommerce-pattern-library#4]
Hi @thomasjbradley :)

It's been a minute, so let's :shipit: !

`Forms and Fields` - Added to library (and sometimes they even work!) I was trying to figure out how to make things like the dropdown menus flexible in length, but didn't come up with something that didn't leave blank lines at the end. Throw that on the "learn-to-do-properly-this summer" pile.

`Navigations & Sections` - This is done, BUT SO SCARILY. I honestly didn't intend for this content to be anything but placeholder, and will likely replace it with a javascript nav tonight. (Assuming I can get it to work)

`Informal browser testing` - was done A WHILE ago, so I'm interested to see how today goes. Might be a yikes. One thing that was interesting to learn was how few browsers seem to support `tel` as anything but a default text input. Also, Edge often broke things on me.

`Headers & footers` - They're done; not happy with the tabbing on them, but the code for the footer isn't too bad. Header is....well, see `Navigations & Sections` and please dear god don't even try to parse those files

`Sharing code with Layouts`- Done and done

`Building Pages w/ Patterns` - So straightforward. BUT ALSO SO GREAT. Definitely feels nice when the patterns are well-built and the pages take 10 minutes to make.

`The leftovers` - I've done most of the cleaning up of my config files, but for some of the longer ones, I'm stuck on how is best to organize them. Alphabetical? (

`Preparing product data` - Got some products! Wheee

`Jekyll generators` - Jekyll made some stuff and it was cool!

`Homepage template` - We got a homepage :D

`Finalizing pattern docs` - I'm not satisfied with my pattern library as an overall theme, but the README has the content it needs to.

`Product list page template` - It's there :D

`Product details page template` - Is also there 😱 

`Checkout form template` - Wooooooo also there; form errors and field labeling are definitely not ideal; would not design this way again.

Annnd that's where we're at! Going to go tackle the surprise pages during this lecture, and then test to find out what 1000 other things are broken (besides the main navigation) :)

Cheers!
MacKenzie

**Comment by thomasjbradley** [comment]
Thanks for the update. I’ve checked off everything except navigations & sections—I don’t see that anywhere in the pattern library.
