### ISSUE TITLE
YAML Truncating Zeroes

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/ecommerce-pattern-library#8]
@thomasjbradley

When I list my prices in YAML, I've got them set as floats, and that results in prices with whole-dollar values getting truncated (ex. $12.00 to $12.0)

Should I be using a different data type?

Cheers!
MacKenzie

**Comment by thomasjbradley** [comment]
You could probably use a string in this situation: `"$12.00"` — unless you’re planning on performing math with those numbers.

**Comment by MacKenzieRose** [comment]
That was the dream for the tables, which I'll end up attempting now that I have the time to learn how to do it :)

My quick and dirty fix for now will probably be just changing the prices 😆
